version: '3.1'

services:

  # MySQL database service
  db:
    image: mysql:8.0
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "alperensah"
    secrets:
      - "mysql_root_pass"
      - "mysql_pass"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql



        # PHP 8.1 FPM service
  php-fpm:
    build: .
    image: php:8.1-fpm
    container_name: php8.1-fpm
    working_dir: /usr/share/nginx/html/
    ports:
      - "9000:9000"
    volumes:
      - ./conf/settings.sh:/home/settings.sh
      - php-fpm:/usr/local/etc/php-fpm.d/
    # cat /usr/local/etc/php-fpm.d/www.conf | grep listen.owner
    # cat /usr/local/etc/php-fpm.d/www.conf | grep listen.group



        # Nginx service
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    # apt update && apt install nano -y
    ports:
      - "80:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - nginx:/usr/share/nginx/html/
    depends_on:
      - "db"
      - "php-fpm"  
    links:
      - "php-fpm"
      - "db"



        #Volumes      
volumes:
  dbdata:
  nginx:
  php-fpm:
    driver: local