version: '3.1'

services:
  # MySQL database service
  db:
    image: mysql:8.0
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    # PHP 8.1 FPM service
  php-fpm:
    image: php:8.1-fpm
    container_name: php8.1-fpm
    working_dir: /usr/share/nginx/html
    volumes:
    - nginx:/usr/share/nginx/html
  # Nginx service
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - nginx:/usr/share/nginx/html
    links:
      - "php-fpm"
volumes:
  dbdata:
  nginx:
  php-fpm:
networks:
  app-network:
    driver: bridge